export const projectList = [
  {
    id: 1,
    title: "Redesign Layout",
    image: "/assets/projects/1.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img2.png", name: "Alex" },
      { image: "/assets/projects/img3.png", name: "Ovi" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "UI/UX Design",
    progress: 80,
  },
  {
    id: 2,
    title: "Redesign",
    image: "/assets/projects/2.svg",
    projectName: "TODO App",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "UI/UX Design",
    progress: 20,
  },
  {
    id: 3,
    title: "Login & Sign Up",
    image: "/assets/projects/3.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "User Map",
    progress: 40,
  },
  {
    id: 4,
    title: "Develop Platform",
    image: "/assets/projects/4.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "User Interstation",
    progress: 80,
  },
  {
    id: 5,
    title: "Redesign Layout",
    image: "/assets/projects/1.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "UI/UX Design",
    progress: 80,
  },
  {
    id: 6,
    title: "Redesign",
    image: "/assets/projects/1.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "UI/UX Design",
    progress: 20,
  },
  {
    id: 7,
    title: "Login & Sign Up",
    image: "/assets/projects/1.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "User Map",
    progress: 40,
  },
  {
    id: 8,
    title: "Develop Platform",
    image: "/assets/projects/1.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "User Interstation",
    progress: 80,
  },
  {
    id: 9,
    title: "Redesign Layout",
    image: "/assets/projects/1.svg",
    projectName: "Netflix",
    status: "Urgent",
    timeline: "20 Feb 24 - 20 Jun 24",
    teams: [
      { image: "/assets/projects/img1.png", name: "John Doe" },
      { image: "/assets/projects/img1.png", name: "Alex" },
      { image: "/assets/projects/img1.png", name: "Ovi" },
    ],
    type: "UI/UX Design",
    progress: 50,
  },
];
